version: '3.8'
services:
  db:
    image: postgres
    restart: always
    container_name: docker_postgres
    environment:
      - POSTGRES_USER=postgrescc
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
