CREATE TABLE IF NOT EXISTS PUBLIC.ORGANISATION (
    NAME TEXT ,
    CHILD_NAME TEXT,
     PRIMARY KEY(NAME, CHILD_NAME)
);

INSERT INTO PUBLIC.ORGANISATION(NAME, CHILD_NAME) VALUES ('Mae', 'Primeira Filha da Mae');
INSERT INTO PUBLIC.ORGANISATION(NAME, CHILD_NAME) VALUES ('Mae', 'Segunda Filha da mesma Mae');
INSERT INTO PUBLIC.ORGANISATION(NAME, CHILD_NAME) VALUES ('Segunda Filha da mesma Mae', 'Neta');
